# Extract Constants from the WebSphere MQ header files
class GenerateConst

  # Extract Constants from Header files
  def GenerateConst.extract_const(filename, const_prefix, start_exp=nil, end_exp=nil)
    constants = []
    active     =
      if start_exp then
        false
      else
        true
      end # Sure there is a better way
    File.open(filename) do |file|
      file.each do |line|
        line.rstrip!
        if line.length > 0 # Skip empty lines
          if active
            break if start_exp && line.match(end_exp)
            # Skip Comment lines, then check for a match
            if (line !~ /^\s*\/\*/) && (match = /\s*#define\s+(#{const_prefix}\w+)[\(\s]+([-\\\w\dx\'\"\s]+)/.match(line))
              constants << [match[1], match[2]]
            end
          else
            next unless line.match(start_exp)
            active = true
          end
        end
      end
    end
    constants
  end

  # Extract MQ Constants from Header files
  def GenerateConst.rb_const(filename, const_prefix, exclude_exp=nil)
    str = ''
    GenerateConst.extract_const(filename, const_prefix).each do |item|
      const, val = item
      next if const.include?('_STRUC_ID')
      next if exclude_exp && const.match(exclude_exp)
      if val.include?('"') || val.include?("'")
        if match = val.match(/(\w+)/)
          val = "'#{match[0]}'"
        else
          val = "''"
        end
      end
      str << "   %-30s = #{val}\n" % const
    end
    str
  end

  def GenerateConst.config(filename, prefix)
    str = "# WMQ::QueueManager execute commands\n"
    str << "execute_commands:\n"
    GenerateConst.extract_const(filename, prefix).each do |item|
      name = item[0].gsub(prefix, '').downcase
      str << "  :%-26s " % "#{name}:"
      match = name.match(/\w+?_([\w_]+)/)
      str << ":#{match[1]}" if match
      str << "\n"
    end
    str
  end

  def GenerateConst.wmq_const(path)
    str = <<END_OF_STRING
################################################################################
#
#  WARNING: DO NOT MODIFY THIS FILE
#
#  This file was generated by generate_const.rb.
#
################################################################################
module WMQ
END_OF_STRING
    [
      ['Connect Options', 'cmqc.h', 'MQCNO_', /(VERSION)|(CONN_TAG)|(HANDLE_SHARE)|(_LENGTH)/],
      ['Open Options', 'cmqc.h', 'MQOO_'],
      ['Close Options', 'cmqc.h', 'MQCO_'],
      ['Match Options', 'cmqc.h', 'MQMO_'],
      ['Message Format Options', 'cmqc.h', 'MQFMT_', /(_ARRAY)/],
      ['Get Message Options', 'cmqc.h', 'MQGMO_', /(VERSION)|(LENGTH)|(MQGMO_BROWSE_HANDLE)|(MQGMO_BROWSE_CO_OP)/],
      ['Transport Types', 'cmqxc.h', 'MQXPT_'],
      ['Report Options', 'cmqc.h', 'MQRO_'],
      ['Message Types', 'cmqc.h', 'MQMT_'],
      ['Expiry', 'cmqc.h', 'MQEI_'],
      ['Feedback Values', 'cmqc.h', 'MQFB_'],
      ['Encoding Values', 'cmqc.h', 'MQENC_', /(MQENC_NORMAL)|(MQENC_REVERSED)|(MQENC_S390)|(MQENC_TNS)/],
      ['Coded Character Set Identifiers', 'cmqc.h', 'MQCCSI_'],
      ['Priority', 'cmqc.h', 'MQPRI_'],
      ['Persistence', 'cmqc.h', 'MQPER_'],
      ['Put Application Types', 'cmqc.h', 'MQAT_'],
      ['Message Flags', 'cmqc.h', 'MQMF_'],
      ['Original Length', 'cmqc.h', 'MQOL_'],
      ['Put Message Options', 'cmqc.h', 'MQPMO_', /(VERSION)|(LENGTH)/],
      ['Put Message Record Fields', 'cmqc.h', 'MQPMRF_', /(VERSION)|(LENGTH)/],
      ['Reason Codes', 'cmqc.h', 'MQRC_'],
    ].each do |item|
      str << "\n# #{item[0]}\n"
      str << GenerateConst.rb_const("#{path}/#{item[1]}", item[2], item[3])
    end
    str << "end\n"
  end

  def GenerateConst.admin_consts(path)
    str = <<END_OF_STRING
################################################################################
#
#  WARNING: DO NOT MODIFY THIS FILE
#
#  This file was generated by generate_const.rb.
#
################################################################################
module WMQ
END_OF_STRING
    str << "# Admin constants from cmqc.h\n"
    [
      ['Object Types', 'cmqc.h', 'MQOT_'],
      ['Security Identifier Types', 'cmqc.h', 'MQSIDT_'],
      ['Channel Types', 'cmqxc.h', 'MQCHT_'],
    ].each do |item|
      str << "\n# #{item[0]}\n"
      str << GenerateConst.rb_const("#{path}/#{item[1]}", item[2], item[3])
    end
    GenerateConst.extract_const(path+'cmqc.h', 'MQ', /Queue\s+Attributes/, /General\s+Constants/).each do |item|
      str << "   %-30s = #{item[1]}\n" % item[0]
    end
    str << "# Admin constants from cmqcfc.h\n"
    GenerateConst.extract_const(path+'cmqcfc.h', 'MQ', /Parameter\s+Values/, /typedef\s+struct/).each do |item|
      str << "   %-30s = #{item[1]}\n" % item[0]
    end
    str << "end\n"
  end

  def self.generate(path, target_path='')
    File.open(File.join(target_path, 'constants_admin.rb'), 'w') { |file| file.write(GenerateConst.admin_consts(path)) }
    puts 'Generated wmq_const_admin.rb'
    File.open(File.join(target_path, 'constants.rb'), 'w') { |file| file.write(GenerateConst.wmq_const(path)) }
    puts 'Generated wmq_const.rb'
  end
end

if $0 == __FILE__
  path = ARGV[0] || raise("Mandatory parameter: 'WebSphere MQ Include path' is missing")
  path = path + '/'
  GenerateConst.generate(path)
end
